-- ADR-0031 Phase 3 — seed _chat_mutation_log_config (20 rules from doc 140340 §SQL)
-- Idempotent: ON CONFLICT DO NOTHING uses the (table_id, column_key) unique index.
-- Rules cover Tickets (1708), _registry (2197), bdd_criteria (7256), bdd_specs (7255),
-- ADR Projects (1699), Bugs (1552). Space-level emission gated by env
-- ROW_MUTATION_LOG_ENABLED_SPACES — empty by default; flipped to "11" on DEV at P3.

INSERT INTO _chat_mutation_log_config (table_id, column_key, template, event_type, enabled) VALUES
  (1708, 'state',                 '🔄 {{display.old}} → {{display.new}}',                                                                                                                                                                  'state_change',    true),
  (1708, 'assigned_to',           '👤 {% if new.assigned_to %}Assigned to {{display.new.name}}{% else %}Unassigned{% endif %}',                                                                                                            'assignment',      true),
  (1708, 'phase',                 '🎯 → {{new.phase}}',                                                                                                                                                                                    'phase_change',    true),
  (1708, 'progress',              '📊 {{old.progress | default: 0}}% → {{new.progress}}%',                                                                                                                                                  'progress',        true),
  (1708, 'priority',              '⚡ Priority {{display.old}} → {{display.new}}',                                                                                                                                                          'priority_change', true),
  (1708, 'due_date',              '⏰ Due {{new.due_date}}',                                                                                                                                                                                'schedule_change', true),
  (1708, 'sealed_at',             '🔒 Sealed by {{actor.name}}',                                                                                                                                                                            'seal',            true),
  (1708, 'type',                  '🏷️ Type {{display.old}} → {{display.new}}',                                                                                                                                                              'type_change',     true),
  (2197, 'status_id',             '📝 Status: {{display.old}} → {{display.new}}',                                                                                                                                                           'state_change',    true),
  (2197, 'name',                  '✏️ Renamed: {{old.name}} → {{new.name}}',                                                                                                                                                                'rename',          true),
  (2197, 'category',              '🗂️ Category: {{display.old}} → {{display.new}}',                                                                                                                                                         'category_change', true),
  (7256, 'status',                '{% if new.status == ''failed'' %}🔴 Regressed: {{old.status}} → failed{% elsif new.status == ''verified'' %}✅ Verified ({{old.status}} → verified){% else %}🔖 {{old.status}} → {{new.status}}{% endif %}', 'state_change',    true),
  (7256, 'priority',              '⚡ Criterion priority {{old.priority}} → {{new.priority}}',                                                                                                                                              'priority_change', true),
  (7256, 'ticket_id',             '🔗 Linked to {{display.new}}',                                                                                                                                                                            'link_change',     true),
  (7255, 'status',                '📚 Spec status: {{old.status}} → {{new.status}}',                                                                                                                                                        'state_change',    true),
  (1699, 'status',                '📋 Project: {{old.status}} → {{new.status}}',                                                                                                                                                            'state_change',    true),
  (1699, 'assigned_orchestrator', '🎼 Orchestrator: {{new.assigned_orchestrator}}',                                                                                                                                                          'assignment',      true),
  (1699, 'completion_percentage', '📊 Project {{old.completion_percentage | default: 0}}% → {{new.completion_percentage}}%',                                                                                                                'progress',        true),
  (1552, 'status',                '🐛 Bug: {{old.status}} → {{new.status}}',                                                                                                                                                                'state_change',    true),
  (1552, 'severity',              '⚠️ Severity: {{old.severity}} → {{new.severity}}',                                                                                                                                                       'severity_change', true)
ON CONFLICT (table_id, column_key) DO NOTHING;
